from typing import Protocol, Any


class CandleSeriesRepository(Protocol):
    def snapshot(self, *, symbol: str, start_ms: int, end_ms: int) -> tuple[int, list[dict[str, Any]]]: ...
    def bounds(self, symbol: str) -> dict[str, Any]: ...
    def context(self, symbol: str) -> dict[str, Any]: ...
    def cached(self, *, symbol: str, interval: str, revision: int, start_ms: int, end_ms: int) -> dict[int, dict[str, Any]]: ...
    def cache(self, *, symbol: str, interval: str, revision: int, items: list[dict[str, Any]]) -> None: ...
