from typing import Any, Protocol


class CollectionRepository(Protocol):
    def policy(self) -> dict[str, Any]: ...
    def configure(self, revision: int, values: dict[str, Any], now_ms: int) -> dict[str, Any]: ...
    def preview(self) -> dict[str, Any]: ...
    def exchange_time_ms(self, now_ms: int) -> int | None: ...
    def start(self, revision: int, pause_schedule_ids: list[str], now_ms: int) -> dict[str, Any]: ...
    def set_control(self, *, scope: str, paused: bool, now_ms: int) -> dict[str, Any]: ...
    def update_runtime(self, *, now_ms: int, blocked_reason: str | None) -> None: ...
    def enroll(self, now_ms: int) -> None: ...
    def discovery_candidates(self, now_ms: int, limit: int) -> list[dict[str, Any]]: ...
    def save_discovery(self, symbol: str, first_ms: int | None, now_ms: int, error: str | None = None, *, data_end_ms: int | None = None) -> None: ...
    def ready_markets(self, now_ms: int, limit: int) -> list[dict[str, Any]]: ...
    def active_count(self) -> int: ...
    def has_unfinished(self, symbol: str, kind: str) -> bool: ...
    def attach_job(self, *, symbol: str, kind: str, start_ms: int, end_ms: int, job_id: str, now_ms: int) -> None: ...
    def reconcile(self, now_ms: int) -> None: ...
    def mark_catalog_requested(self, now_ms: int) -> None: ...
    def status(self, now_ms: int) -> dict[str, Any]: ...
    def markets(self, *, search: str, after: str | None, limit: int) -> dict[str, Any]: ...
    def set_excluded(self, symbol: str, excluded: bool, now_ms: int) -> None: ...
    def touch_market(self, symbol: str, now_ms: int) -> None: ...
    def retryable_segments(self, *, symbol: str | None, now_ms: int, automatic: bool) -> list[dict[str, Any]]: ...
    def reattach_job(self, segment_id: str, job_id: str, now_ms: int) -> None: ...
