from contextlib import AbstractContextManager
from typing import Protocol, Any


class ExecutionLost(RuntimeError):
    """The caller no longer owns this execution."""


class ExecutionInterrupted(RuntimeError):
    """A control request or shutdown interrupted execution."""


class JobConflict(ValueError):
    pass


class MaintenanceActive(RuntimeError):
    pass


class JobExecutionStore(Protocol):
    def atomic(self) -> AbstractContextManager: ...
    def admission(self) -> AbstractContextManager: ...
    def maintenance(self) -> AbstractContextManager: ...
    def batch(self, job_id: str, batch_id: str) -> AbstractContextManager: ...
    def enqueue(self, key: str | None, payload: dict, create: Any) -> str: ...
    def claim(self, owner: str, *, job_id: str | None = None) -> tuple[str, str] | None: ...
    def scope(self, job_id: str, token: str, stop_event: Any) -> AbstractContextManager: ...
    def checkpoint(self) -> AbstractContextManager: ...
    def heartbeat(self, owner: str, *, job_ids: list[str] | None = None) -> None: ...
    def recover(self) -> int: ...
    def release(self, job_id: str, token: str) -> None: ...
    def load_plan(self, job_id: str) -> dict | None: ...
    def save_plan(self, job_id: str, plan: dict) -> None: ...
    def record_trigger(self, schedule_id: str, due_at_ms: int) -> bool: ...
    def load_request(self, job_id: str) -> dict | None: ...
    def save_request(self, job_id: str, payload: dict) -> None: ...
    def set_query_bounds(self, job_id: str, plan: Any) -> None: ...
