from typing import Any, Protocol

from app.application.models.market_catalog import CatalogSnapshot


class MarketCatalogRepository(Protocol):
    def request_sync(self, *, key: str | None, allow_large_change: bool, now_ms: int) -> dict[str, Any]: ...
    def claim_sync(self, *, now_ms: int) -> dict[str, Any] | None: ...
    def renew_sync(self, run_id: str, token: str, *, now_ms: int) -> None: ...
    def publish(self, run_id: str, token: str, snapshot: CatalogSnapshot, *, now_ms: int) -> dict[str, Any]: ...
    def fail_sync(self, run_id: str, token: str, error: str, *, now_ms: int) -> None: ...
    def get_run(self, run_id: str) -> dict[str, Any] | None: ...
    def latest_run(self) -> dict[str, Any] | None: ...
    def list_symbols(self, *, search: str, status: str | None, after: str | None, limit: int) -> dict[str, Any]: ...
